INSERT INTO clubs(description, club_rating)
SELECT DISTINCT club_team, club_rating FROM jogadores
	WHERE club_team IS NOT NULL;


INSERT INTO national_team(description, national_rating)
SELECT DISTINCT national_team, national_rating FROM jogadores
	WHERE national_team IS NOT NULL;



INSERT INTO nationality(description)
SELECT DISTINCT nationality FROM jogadores
	WHERE nationality IS NOT NULL;

insert into players (id ,
	name,
	full_name,
	birth_date,
	age,
	height_cm,
	weight_kgs,
	code_nationality,
	overall_rating,
	potential,
	value_euro,
	wage_euro,
    preferred_foot,
	international_reputation,
	weak_foot,
	skill_moves,
	work_rate_defense,  
	work_rate_attack,
	body_type,
	release_clause_euro,
	code_club_team,
	club_position,
	club_jersey_number,
	club_join_date,
	contract_end_year,
	code_national_team,
	national_team_position,
	national_jersey_number,
	crossing,
	finishing,
	heading_accuracy,
	short_passing,
	volley,
	dribbling,
	curve,
	freekick_accuracy,
	long_passing,
	ball_control,
	acceleration,
	sprint_speed,
	agility,
	reactions,
	balance,
	shot_power,
	jumping,
	stamina,
	strength,
	long_shots,
	agression,
	interceptation,
	positioning,
	vision,
	penalties,
	composure,
	marking,
	standing_tackle,
	sliding_tackle,
	gk_diving,
	gk_handing,
	gk_kiking,
	gk_positioning,
	gk_reflexes,
	ls,
	st,
	rs,
	lw,
	lf,
	cf,
	rf,
	rw,
	lam,
	cam,
	ram,
	lm,
	lcm,
	cm,
	rcm,
	rm,
	lwb,
	ldm,
	cdm,
	rdm,
	rwb,
	lb,
	lcb,
	cb,
	rcb,
	rb
)
	SELECT id ,
	name,
	full_name,
	birth_date,
	age,
	height_cm,
	weight_kgs,
	code_nationality,
	overall_rating,
	potential,
	value_euro,
	wage_euro,
    preferred_foot,
	international_reputation,
	weak_foot,
	skill_moves,
	trim(substring(work_rate from 1 for position ('/' in work_rate) - 1) ),
	trim(substring(work_rate from position ('/' in work_rate) + 1 )), 
	body_type,
	release_clause_euro,
	code_club_team,
	club_position,
	club_jersey_number,
	club_join_date,
	contract_end_year,
	code_national_team,
	national_team_position,
	national_jersey_number,
	crossing,
	finishing,
	heading_accuracy,
	short_passing,
	volley,
	dribbling,
	curve,
	freekick_accuracy,
	long_passing,
	ball_control,
	acceleration,
	sprint_speed,
	agility,
	reactions,
	balance,
	shot_power,
	jumping,
	stamina,
	strength,
	long_shots,
	agression,
	interceptation,
	positioning,
	vision,
	penalties,
	composure,
	marking,
	standing_tackle,
	sliding_tackle,
	gk_diving,
	gk_handing,
	gk_kiking,
	gk_positioning,
	gk_reflexes,
	ls,
	st,
	rs,
	lw,
	lf,
	cf,
	rf,
	rw,
	lam,
	cam,
	ram,
	lm,
	lcm,
	cm,
	rcm,
	rm,
	lwb,
	ldm,
	cdm,
	rdm,
	rwb,
	lb,
	lcb,
	cb,
	rcb,
	rb FROM jogadores left JOIN nationality nations ON trim(jogadores.nationality) = trim(nations.description)
	left JOIN clubs ON trim(jogadores.club_team) = trim(clubs.description)
	left JOIN national_team ON trim(jogadores.national_team) = trim(national_team.description);